CREATE TABLE IF NOT EXISTS foundations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  location text,
  email text,
  phone text,
  logo_url text,
  verified integer NOT NULL DEFAULT 1,
  available_slots text,
  created_at text NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'usuario',
  avatar text,
  foundation_id bigint REFERENCES foundations(id) ON DELETE SET NULL,
  created_at text NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL,
  breed text,
  age text NOT NULL,
  gender text,
  weight text,
  location text NOT NULL,
  image text NOT NULL,
  tone text NOT NULL DEFAULT 'bg-[#e9d8c8]',
  vaccinated integer NOT NULL DEFAULT 0,
  sterilized integer NOT NULL DEFAULT 0,
  personality text,
  about text,
  good_with text,
  energy text,
  foundation_id bigint REFERENCES foundations(id) ON DELETE CASCADE,
  published_by bigint REFERENCES users(id) ON DELETE SET NULL,
  adoption_state text NOT NULL DEFAULT 'en_adopcion',
  created_at text NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pet_id bigint NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
  created_at text NOT NULL DEFAULT now(),
  UNIQUE (user_id, pet_id)
);

CREATE TABLE IF NOT EXISTS adoption_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pet_id bigint NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pendiente',
  message text,
  scheduled_date text,
  application text,
  created_at text NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_pets_type ON pets(type);
CREATE INDEX IF NOT EXISTS idx_pets_foundation ON pets(foundation_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_requests_user ON adoption_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_requests_pet ON adoption_requests(pet_id);

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

ALTER TABLE public.foundations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.pets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.adoption_requests DISABLE ROW LEVEL SECURITY;
