export type CatalogPet = {
  id?: number
  name: string
  type: 'Perro' | 'Gato'
  age: string
  location: string
  image: string
  tone: string
  breed: string | null
  gender: 'Macho' | 'Hembra' | null
  weight: string | null
  vaccinated: boolean
  sterilized: boolean
  personality: string[]
  about: string | null
  good_with: string[]
  energy: 'Baja' | 'Media' | 'Alta' | null
}

export const FALLBACK_PETS: CatalogPet[] = [
  {
    id: 9001,
    name: 'Simba',
    type: 'Gato',
    age: '2 años',
    location: 'Providencia, Santiago',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#ead9c6]',
    breed: 'Naranja atigrado',
    gender: 'Macho',
    weight: '5.1 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Curioso', 'Cariñoso', 'Vocal'],
    about: 'Simba es un gato naranja muy sociable. Le encanta seguirte por la casa y sentarse junto a la ventana.',
    good_with: ['Niños', 'Gatos', 'Ancianos'],
    energy: 'Media',
  },
  {
    id: 9002,
    name: 'Daisy',
    type: 'Perro',
    age: '3 años',
    location: 'Las Condes, Santiago',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#e6eee1]',
    breed: 'Cocker Spaniel',
    gender: 'Hembra',
    weight: '13 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Dulce', 'Juguetona', 'Sociable'],
    about: 'Daisy adora los paseos cortos y las siestas en el sofá. Es ideal para departamento con rutina estable.',
    good_with: ['Niños', 'Otros perros', 'Ancianos'],
    energy: 'Media',
  },
  {
    id: 9003,
    name: 'Max',
    type: 'Perro',
    age: '5 años',
    location: 'Ñuñoa, Santiago',
    image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#e9d8c8]',
    breed: 'Pastor alemán mestizo',
    gender: 'Macho',
    weight: '32 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Leal', 'Protector', 'Inteligente'],
    about: 'Max ya está educado y busca una familia activa. Disfruta caminatas largas y aprender trucos nuevos.',
    good_with: ['Niños', 'Adultos'],
    energy: 'Alta',
  },
  {
    id: 9004,
    name: 'Mimi',
    type: 'Gato',
    age: '4 años',
    location: 'Valparaíso',
    image: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#d9e2d3]',
    breed: 'British Shorthair',
    gender: 'Hembra',
    weight: '4.8 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Tranquila', 'Independiente', 'Mimosa'],
    about: 'Mimi es una gata serena, perfecta para hogares calmados. Le gusta observar desde lo alto y recibir cepillados.',
    good_with: ['Ancianos', 'Gatos'],
    energy: 'Baja',
  },
  {
    id: 9005,
    name: 'Chispa',
    type: 'Perro',
    age: '8 meses',
    location: 'Narvarte',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#fde4dc]',
    breed: 'Mestiza pequeña',
    gender: 'Hembra',
    weight: '6 kg',
    vaccinated: true,
    sterilized: false,
    personality: ['Traviesa', 'Alegre', 'Cariñosa'],
    about: 'Chispa es una cachorra llena de energía que ya convive con personas y otros perros en el refugio.',
    good_with: ['Niños', 'Otros perros'],
    energy: 'Alta',
  },
  {
    id: 9006,
    name: 'Otto',
    type: 'Perro',
    age: '9 años',
    location: 'Del Valle',
    image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#ead9c6]',
    breed: 'Schnauzer mini',
    gender: 'Macho',
    weight: '8 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Tranquilo', 'Cariñoso', 'Obediente'],
    about: 'Otto es un senior muy noble. Busca un hogar sin prisas, con mimos y paseos cortos.',
    good_with: ['Ancianos', 'Niños'],
    energy: 'Baja',
  },
  {
    id: 9007,
    name: 'Pipa',
    type: 'Gato',
    age: '6 meses',
    location: 'Álvaro Obregón',
    image: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#e6eee1]',
    breed: 'Criolla atigrada',
    gender: 'Hembra',
    weight: '2.4 kg',
    vaccinated: true,
    sterilized: false,
    personality: ['Juguetona', 'Curiosa', 'Social'],
    about: 'Pipa es una gatita joven que se lleva bien con perros tranquilos y le encanta perseguir plumeros.',
    good_with: ['Niños', 'Gatos', 'Otros perros'],
    energy: 'Alta',
  },
  {
    id: 9008,
    name: 'Thor',
    type: 'Perro',
    age: '4 años',
    location: 'Iztapalapa',
    image: 'https://images.unsplash.com/photo-1568572933382-74d440642117?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#e9d8c8]',
    breed: 'Husky mestizo',
    gender: 'Macho',
    weight: '27 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Energético', 'Sociable', 'Aventurero'],
    about: 'Thor necesita espacio para correr y una familia que disfrute salir al parque todos los días.',
    good_with: ['Otros perros', 'Niños'],
    energy: 'Alta',
  },
  {
    id: 9009,
    name: 'Greta',
    type: 'Gato',
    age: '7 años',
    location: 'Coyoacán',
    image: 'https://images.unsplash.com/photo-1472491235688-bdc81a63246e?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#d9e2d3]',
    breed: 'Siamés mestiza',
    gender: 'Hembra',
    weight: '3.9 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Elegante', 'Tranquila', 'Afectuosa'],
    about: 'Greta es una gata adulta muy educada. Prefiere hogares silenciosos y se adapta rápido a departamentos.',
    good_with: ['Ancianos', 'Gatos'],
    energy: 'Baja',
  },
  {
    id: 9010,
    name: 'Benny',
    type: 'Perro',
    age: '1 año',
    location: 'Roma Norte',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#fde4dc]',
    breed: 'Beagle mestizo',
    gender: 'Macho',
    weight: '11 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Olfateador', 'Alegre', 'Cariñoso'],
    about: 'Benny es joven, sociable y ya sabe caminar con correa. Ideal para una primera adopción.',
    good_with: ['Niños', 'Otros perros', 'Gatos'],
    energy: 'Alta',
  },
  {
    id: 9011,
    name: 'Oliva',
    type: 'Gato',
    age: '3 años',
    location: 'Condesa',
    image: 'https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#ead9c6]',
    breed: 'Carey',
    gender: 'Hembra',
    weight: '4.1 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Independiente', 'Juguetona', 'Cariñosa'],
    about: 'Oliva convive con otros gatos y busca un hogar donde pueda tener ventanas y rascadores.',
    good_with: ['Gatos', 'Niños'],
    energy: 'Media',
  },
  {
    id: 9012,
    name: 'Cookie',
    type: 'Perro',
    age: '6 años',
    location: 'Polanco',
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=900&q=85',
    tone: 'bg-[#e6eee1]',
    breed: 'French Poodle',
    gender: 'Hembra',
    weight: '7 kg',
    vaccinated: true,
    sterilized: true,
    personality: ['Mimosa', 'Tranquila', 'Inteligente'],
    about: 'Cookie está acostumbrada a departamento, no ladra en exceso y le encanta que la peinen.',
    good_with: ['Ancianos', 'Niños'],
    energy: 'Baja',
  },
]

export function mergeCatalogPets(apiPets: CatalogPet[]): CatalogPet[] {
  if (apiPets.length >= 12) return apiPets
  const names = new Set(apiPets.map((p) => p.name.toLowerCase()))
  const extra = FALLBACK_PETS.filter((p) => !names.has(p.name.toLowerCase()))
  return [...apiPets, ...extra]
}
